services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: postgres://user:password@db:5432/taxdb?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taxdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d taxdb"]
      interval: 5s
      retries: 5

  test-db:
    image: postgres:16
    volumes:
      - test_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tax_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tax_test"]
      interval: 5s
      retries: 5

  tester:
    build:
      context: .
      dockerfile: Dockerfile
      target: tester
    environment:
      TEST_DB_URL: postgres://user:password@test-db:5432/tax_test?sslmode=disable
    depends_on:
      - test-db

volumes:
  db_data:
  test_db_data:
